package Ventanas;


import Clases.Clientes;
import Clases.Utilidades;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilda
 */
public class Actualizar_Cliente_Window extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    String[] columna = {"Id Cliente", "Nombre", "Telefono", "Correo"};
    public Actualizar_Cliente_Window() {
        initComponents();
        panel_transparent.setBackground(new Color (212,176,155,200));
        panel_Transparent_White1.setBackground(new Color (255,255,255,200));
        Tclientes.setModel(new DefaultTableModel(Clases.Utilidades.FiltrarClientes(new int[] {0, 0, 0},new String[] {"", "", ""}, Clases.Clientes.clientes), columna));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_transparent = new javax.swing.JPanel();
        label_Nombre = new javax.swing.JLabel();
        TFnom = new javax.swing.JTextField();
        label_No_contacto = new javax.swing.JLabel();
        TFtel = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        TFcorreo = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JLabel();
        panel_Transparent_White1 = new javax.swing.JPanel();
        Registros = new javax.swing.JLabel();
        HOME_ICON = new javax.swing.JLabel();
        Panel_Tabla = new javax.swing.JPanel();
        Label_Lista_Clientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tclientes = new javax.swing.JTable();
        label_Borered = new javax.swing.JLabel();
        TFnom2 = new javax.swing.JTextField();
        label_Nombre2 = new javax.swing.JLabel();
        label_No_Contacto = new javax.swing.JLabel();
        TFtel2 = new javax.swing.JTextField();
        label_Email2 = new javax.swing.JLabel();
        TFcorreo2 = new javax.swing.JTextField();
        btn_Actualizar = new javax.swing.JLabel();
        btn_Eliminar = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_transparent.setBackground(new java.awt.Color(212, 176, 155));
        panel_transparent.setEnabled(false);
        panel_transparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre.setText("NOMBRE:");
        panel_transparent.add(label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        TFnom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFnom.setBorder(null);
        TFnom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomActionPerformed(evt);
            }
        });
        panel_transparent.add(TFnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 390, 39));

        label_No_contacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_contacto.setText("NO. CONTACTO:");
        panel_transparent.add(label_No_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        TFtel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFtel.setBorder(null);
        TFtel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_transparent.add(TFtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 229, 39));

        label_Email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Email.setText("CORREO ELECTRONICO:");
        panel_transparent.add(label_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, 30));

        TFcorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFcorreo.setBorder(null);
        TFcorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_transparent.add(TFcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 420, 40));

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_White.png"))); // NOI18N
        btn_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseExited(evt);
            }
        });
        panel_transparent.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        panel_Transparent_White1.setBackground(new java.awt.Color(255, 255, 255));

        Registros.setFont(new java.awt.Font("Palatino Linotype", 1, 40)); // NOI18N
        Registros.setForeground(new java.awt.Color(105, 87, 86));
        Registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registros.setText("Perfil Cliente ");
        Registros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HOME_ICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON.png"))); // NOI18N
        HOME_ICON.setFocusable(false);
        HOME_ICON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HOME_ICON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_Transparent_White1Layout = new javax.swing.GroupLayout(panel_Transparent_White1);
        panel_Transparent_White1.setLayout(panel_Transparent_White1Layout);
        panel_Transparent_White1Layout.setHorizontalGroup(
            panel_Transparent_White1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Transparent_White1Layout.createSequentialGroup()
                .addComponent(HOME_ICON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );
        panel_Transparent_White1Layout.setVerticalGroup(
            panel_Transparent_White1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Transparent_White1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_Transparent_White1Layout.createSequentialGroup()
                .addComponent(HOME_ICON)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panel_transparent.add(panel_Transparent_White1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        Panel_Tabla.setBackground(new java.awt.Color(128, 76, 46));

        Label_Lista_Clientes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Label_Lista_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Label_Lista_Clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Lista_Clientes.setText("LISTA DE CLIENTES");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        Tclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente_Nombre", "Numero_tel", "Correo_electronico", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tclientes);

        javax.swing.GroupLayout Panel_TablaLayout = new javax.swing.GroupLayout(Panel_Tabla);
        Panel_Tabla.setLayout(Panel_TablaLayout);
        Panel_TablaLayout.setHorizontalGroup(
            Panel_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(Panel_TablaLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(Label_Lista_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        Panel_TablaLayout.setVerticalGroup(
            Panel_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Lista_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        panel_transparent.add(Panel_Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 830, 130));

        label_Borered.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Borered.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Buscar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Palatino Linotype", 0, 12))); // NOI18N
        panel_transparent.add(label_Borered, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 920, 270));

        TFnom2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFnom2.setBorder(null);
        TFnom2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_transparent.add(TFnom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 740, 40));

        label_Nombre2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre2.setText("NOMBRE:");
        panel_transparent.add(label_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, 30));

        label_No_Contacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_Contacto.setText("NO. CONTACTO:");
        panel_transparent.add(label_No_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 130, 30));

        TFtel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFtel2.setBorder(null);
        TFtel2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_transparent.add(TFtel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 740, 40));

        label_Email2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Email2.setText("CORREO ELECTRONICO:");
        panel_transparent.add(label_Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 180, 30));

        TFcorreo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFcorreo2.setBorder(null);
        TFcorreo2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_transparent.add(TFcorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 740, 40));

        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Actualizar_White.png"))); // NOI18N
        btn_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ActualizarMouseExited(evt);
            }
        });
        panel_transparent.add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, -1, -1));

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Eliminar_Cliente_White.png"))); // NOI18N
        btn_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EliminarMouseExited(evt);
            }
        });
        panel_transparent.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, -1));

        getContentPane().add(panel_transparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds_Fondo/bg_Registros.jpg"))); // NOI18N
        bgImage.setText("jLabel1");
        bgImage.setMaximumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setMinimumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void btn_BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseEntered
        // TODO add your handling code here:
         btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_Brown.png"))); 
    }//GEN-LAST:event_btn_BuscarMouseEntered

    private void btn_BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseExited
        // TODO add your handling code here:
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_White.png"))); 
        
    }//GEN-LAST:event_btn_BuscarMouseExited

    private void btn_ActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarMouseEntered
        // TODO add your handling code here:
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Actualizar_Brown.png")));
    }//GEN-LAST:event_btn_ActualizarMouseEntered

    private void btn_ActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarMouseExited
        // TODO add your handling code here:
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Actualizar_White.png")));
    }//GEN-LAST:event_btn_ActualizarMouseExited

    private void HOME_ICONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseClicked
        SQL.Guardar.guardar();
        new Home_Windows().setVisible(true);
        dispose();
    }//GEN-LAST:event_HOME_ICONMouseClicked

    private void HOME_ICONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseEntered
        // TODO add your handling code here:
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON_LIGHTBROWN.png")));
    }//GEN-LAST:event_HOME_ICONMouseEntered

    private void HOME_ICONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseExited
        // TODO add your handling code here:
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON.png")));
    }//GEN-LAST:event_HOME_ICONMouseExited

    private void btn_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseClicked
        int f1 = TFnom.getText().equals("")? 0: 1;
        int f2 = TFtel.getText().equals("")? 0: 1;
        int f3 = TFcorreo.getText().equals("")? 0: 1;
        
        int[] filtros = {f1, f2, f3};
        
        String[] values = {TFnom.getText(), TFtel.getText(), TFcorreo.getText()};
        
        Tclientes.setModel(new DefaultTableModel(Clases.Utilidades.FiltrarClientes(filtros,values, Clases.Clientes.clientes), columna));
    }//GEN-LAST:event_btn_BuscarMouseClicked

    private void TFnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomActionPerformed

    private void TclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TclientesMouseClicked
        int sl = Tclientes.getSelectedRow();
        switch(sl){
            case -1 -> {
                TFnom2.setText("");
                TFtel2.setText("");
                TFcorreo2.setText("s");
            }
            default -> {
                TFnom2.setText(Tclientes.getValueAt(sl, 1).toString());
                TFtel2.setText(Tclientes.getValueAt(sl, 2).toString());
                TFcorreo2.setText(Tclientes.getValueAt(sl, 3).toString());
            }
        }
    }//GEN-LAST:event_TclientesMouseClicked

    private void btn_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarMouseClicked
        Object[] val = new String[4];
        
        val[0] = String.valueOf(Tclientes.getValueAt(Tclientes.getSelectedRow(), 0));
        val[1] = TFnom2.getText();
        val[2] = TFtel2.getText();
        val[3] = TFcorreo2.getText();
        
        new Clientes().modificar(val);
        Tclientes.setModel(new DefaultTableModel(Clases.Utilidades.FiltrarClientes(new int[] {0, 0, 0},new String[] {"", "", ""}, Clases.Clientes.clientes), columna));
    }//GEN-LAST:event_btn_ActualizarMouseClicked

    private void btn_EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarMouseEntered
        // TODO add your handling code here:
        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Eliminar_Cliente_Brown.png")));
    }//GEN-LAST:event_btn_EliminarMouseEntered

    private void btn_EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarMouseExited
        // TODO add your handling code here:
        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Eliminar_Cliente_White.png")));
    }//GEN-LAST:event_btn_EliminarMouseExited

    private void btn_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarMouseClicked
        if(Tclientes.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione una cita");
        }else{
            int o = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere eliminar esta cita?");
            
            if(o == JOptionPane.YES_OPTION){
                new Clientes().eliminar(new String[] {Tclientes.getValueAt(Tclientes.getSelectedRow(), 0).toString()});
                Tclientes.setModel(new DefaultTableModel(Clases.Utilidades.FiltrarClientes(new int[] {0, 0, 0},new String[] {"", "", ""}, Clases.Clientes.clientes), columna));
                TFnom.setText("");
                TFtel.setText("");
                TFcorreo.setText("");
            }
        }
    }//GEN-LAST:event_btn_EliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_Cliente_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_Cliente_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_Cliente_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_Cliente_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_Cliente_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HOME_ICON;
    private javax.swing.JLabel Label_Lista_Clientes;
    private javax.swing.JPanel Panel_Tabla;
    private javax.swing.JLabel Registros;
    private javax.swing.JTextField TFcorreo;
    private javax.swing.JTextField TFcorreo2;
    private javax.swing.JTextField TFnom;
    private javax.swing.JTextField TFnom2;
    private javax.swing.JTextField TFtel;
    private javax.swing.JTextField TFtel2;
    private javax.swing.JTable Tclientes;
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btn_Actualizar;
    private javax.swing.JLabel btn_Buscar;
    private javax.swing.JLabel btn_Eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Borered;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Email2;
    private javax.swing.JLabel label_No_Contacto;
    private javax.swing.JLabel label_No_contacto;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_Nombre2;
    private javax.swing.JPanel panel_Transparent_White1;
    private javax.swing.JPanel panel_transparent;
    // End of variables declaration//GEN-END:variables
    private int xx, xy;
}
