package Ventanas;


import Clases.Citas;
import Clases.Utilidades;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilda
 */
public class Facturacion_Windows  extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String[] columnas = {"Id", "Fecha", "Hora"};
    String id_cliente;
    String nombre;
    String telefono;
    String correo;
    public Facturacion_Windows(String[] set) {
        initComponents();
        panel_transparent.setBackground(new Color (212,176,155,200));
        panel_Transparent1.setBackground(new Color (255,255,255,200));
        //panel_Transparent2.setBackground(new Color (255,255,255,200));
        //panel_Transparent3.setBackground(new Color (255,255,255,200));
        this.id_cliente = set[0];
        this.nombre = set[1];
        this.telefono = set[2];
        this.correo = set[3];
        
        TFnom.setText(set[1]);
        TFtel.setText(set[2]);
        
        String fecha = "";
            
        DCfecha.setMinSelectableDate(new Date());
        
        Tcitas.setModel(new DefaultTableModel(Utilidades.FiltrarCitas(new String[] {"", id_cliente}, Citas.citas), columnas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_transparent = new javax.swing.JPanel();
        label_Nombre = new javax.swing.JLabel();
        panel_Transparent1 = new javax.swing.JPanel();
        HOME_ICON = new javax.swing.JLabel();
        label_titulo_Facturacion1 = new javax.swing.JLabel();
        Label_Fecha = new javax.swing.JLabel();
        DCfecha = new com.toedter.calendar.JDateChooser();
        TFnom = new javax.swing.JTextField();
        Label_No_Contacto = new javax.swing.JLabel();
        Panel_Tab = new javax.swing.JPanel();
        Label_Lista_clientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tcitas = new javax.swing.JTable();
        btn_Buscar = new javax.swing.JLabel();
        TFtel = new javax.swing.JTextField();
        panel_ResumenServ = new javax.swing.JPanel();
        label_Titlulo = new javax.swing.JLabel();
        scrollpanel_Resumen = new javax.swing.JScrollPane();
        Tresumen = new javax.swing.JTable();
        TFtotal = new javax.swing.JTextField();
        label_total = new javax.swing.JLabel();
        btn_Facturar = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_transparent.setBackground(new java.awt.Color(212, 176, 155));
        panel_transparent.setEnabled(false);
        panel_transparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre.setText("NOMBRE:");
        panel_transparent.add(label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, -1));

        panel_Transparent1.setBackground(new java.awt.Color(255, 255, 255));

        HOME_ICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON.png"))); // NOI18N
        HOME_ICON.setFocusable(false);
        HOME_ICON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HOME_ICON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseExited(evt);
            }
        });

        label_titulo_Facturacion1.setBackground(new java.awt.Color(105, 87, 86));
        label_titulo_Facturacion1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        label_titulo_Facturacion1.setForeground(new java.awt.Color(105, 87, 86));
        label_titulo_Facturacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo_Facturacion1.setText("Facturación");
        label_titulo_Facturacion1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_titulo_Facturacion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_titulo_Facturacion1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panel_Transparent1Layout = new javax.swing.GroupLayout(panel_Transparent1);
        panel_Transparent1.setLayout(panel_Transparent1Layout);
        panel_Transparent1Layout.setHorizontalGroup(
            panel_Transparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Transparent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420)
                .addComponent(label_titulo_Facturacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        panel_Transparent1Layout.setVerticalGroup(
            panel_Transparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Transparent1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Transparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HOME_ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_titulo_Facturacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_transparent.add(panel_Transparent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 60));

        Label_Fecha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Label_Fecha.setText("FECHA:");
        panel_transparent.add(Label_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 60, -1));

        DCfecha.setBackground(new java.awt.Color(255, 255, 255));
        DCfecha.setDateFormatString("y,MMMM,d");
        DCfecha.setMaxSelectableDate(new java.util.Date(1717218081000L));
        DCfecha.setMinSelectableDate(new java.util.Date(1672549281000L));
        panel_transparent.add(DCfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 170, 40));

        TFnom.setEditable(false);
        panel_transparent.add(TFnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 630, 40));

        Label_No_Contacto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Label_No_Contacto.setText("NO. CONTACTO:");
        panel_transparent.add(Label_No_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, -1));

        Panel_Tab.setBackground(new java.awt.Color(128, 76, 46));

        Label_Lista_clientes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Label_Lista_clientes.setForeground(new java.awt.Color(255, 255, 255));
        Label_Lista_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Lista_clientes.setText("Lista de Citas");

        Tcitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente_Nombre", "Numero_Tel", "Servicios", "Compras de productos", "Total", "Fecha"
            }
        ));
        Tcitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tcitas);

        javax.swing.GroupLayout Panel_TabLayout = new javax.swing.GroupLayout(Panel_Tab);
        Panel_Tab.setLayout(Panel_TabLayout);
        Panel_TabLayout.setHorizontalGroup(
            Panel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Lista_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
        Panel_TabLayout.setVerticalGroup(
            Panel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Label_Lista_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        panel_transparent.add(Panel_Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 1040, 190));

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_White.png"))); // NOI18N
        btn_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseExited(evt);
            }
        });
        panel_transparent.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 220, 40));

        TFtel.setEditable(false);
        TFtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtelActionPerformed(evt);
            }
        });
        panel_transparent.add(TFtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 340, 40));

        panel_ResumenServ.setBackground(new java.awt.Color(255, 255, 255));
        panel_ResumenServ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panel_ResumenServ.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Titlulo.setBackground(new java.awt.Color(255, 255, 255));
        label_Titlulo.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        label_Titlulo.setForeground(new java.awt.Color(128, 76, 46));
        label_Titlulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Titlulo.setText("Resumen de Servicios");
        panel_ResumenServ.add(label_Titlulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 470, 30));

        scrollpanel_Resumen.setBackground(new java.awt.Color(128, 76, 46));

        Tresumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanel_Resumen.setViewportView(Tresumen);
        if (Tresumen.getColumnModel().getColumnCount() > 0) {
            Tresumen.getColumnModel().getColumn(1).setMinWidth(60);
            Tresumen.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        panel_ResumenServ.add(scrollpanel_Resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 870, 160));

        TFtotal.setEditable(false);
        TFtotal.setBackground(new java.awt.Color(255, 255, 255));
        panel_ResumenServ.add(TFtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 120, 30));

        label_total.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_total.setText("TOTAL A PAGAR:");
        panel_ResumenServ.add(label_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 130, 20));

        panel_transparent.add(panel_ResumenServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 890, 240));

        btn_Facturar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Facturar_White_Facturacion.png"))); // NOI18N
        btn_Facturar.setMaximumSize(new java.awt.Dimension(204, 36));
        btn_Facturar.setMinimumSize(new java.awt.Dimension(200, 36));
        btn_Facturar.setPreferredSize(new java.awt.Dimension(204, 36));
        btn_Facturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FacturarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FacturarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_FacturarMouseExited(evt);
            }
        });
        panel_transparent.add(btn_Facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 200, -1));

        getContentPane().add(panel_transparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 720));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds_Fondo/bg_Registros.jpg"))); // NOI18N
        bgImage.setText("jLabel1");
        bgImage.setMaximumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setMinimumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void btn_BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseEntered
        // TODO add your handling code here:
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_Brown.png")));
    }//GEN-LAST:event_btn_BuscarMouseEntered

    private void btn_BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseExited
        // TODO add your handling code here:
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_White.png")));
    }//GEN-LAST:event_btn_BuscarMouseExited

    private void HOME_ICONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseEntered
        // TODO add your handling code here:
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON_LIGHTBROWN.png")));
    }//GEN-LAST:event_HOME_ICONMouseEntered

    private void HOME_ICONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseExited
        // TODO add your handling code here:
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON.png")));
    }//GEN-LAST:event_HOME_ICONMouseExited

    private void HOME_ICONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseClicked
        SQL.Guardar.guardar();
        new Home_Windows().setVisible(true);
        dispose();
    }//GEN-LAST:event_HOME_ICONMouseClicked

    private void TFtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtelActionPerformed

    private void btn_FacturarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FacturarMouseEntered
        // TODO add your handling code here:
       btn_Facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Facturar_Brown_Facturacion.png"))); 
    }//GEN-LAST:event_btn_FacturarMouseEntered

    private void btn_FacturarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FacturarMouseExited
        // TODO add your handling code here:
        btn_Facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Facturar_White_Facturacion.png"))); 
    }//GEN-LAST:event_btn_FacturarMouseExited

    private void btn_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseClicked
        String fecha = "";
            
        LocalDate com = DCfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
        int year = com.getYear();
        int month = com.getMonthValue();
        int day = com.getDayOfMonth();
            
        String hora = "00:00";
            
        fecha += year +"-";
            
        if(month < 10){
            fecha += "0" + month + "-";
        }else{
            fecha += month + "-";
        }
            
        if(day < 10){
            fecha += "0" + day; 
        }else{
            fecha += day;
        }
            
        fecha += " " + hora;
        
        Tcitas.setModel(new DefaultTableModel(Utilidades.FiltrarCitas(new String[] {fecha, id_cliente}, Citas.citas), columnas));
    }//GEN-LAST:event_btn_BuscarMouseClicked

    private void TcitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcitasMouseClicked
        int sl = Tcitas.getSelectedRow();
        
        Citas cita = new Citas();
        for(int i = 0; i < Citas.citas.size(); i++){
            if(Citas.citas.get(i).getId() == Integer.parseInt(Tcitas.getValueAt(sl, 0).toString())){
                cita = Citas.citas.get(i);
                break;
            }
        }
        
        String[][] modelo = new String[cita.getLista_servicios().size()][2];
        for(int i = 0; i < cita.getLista_servicios().size(); i++){
            modelo[i][0] = cita.getLista_servicios().get(i).getNombre();
            modelo[i][1] = String.valueOf(cita.getLista_servicios().get(i).getPrecio());
        }
        
        Tresumen.setModel(new DefaultTableModel(modelo, new String[] {"Servicio", "Precio"}));
        
        int total = 0;
        
        for(int i = 0; i < Tresumen.getRowCount(); i++){
            total += Integer.parseInt(Tresumen.getValueAt(i, 1).toString());
        }
            
        TFtotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_TcitasMouseClicked

    private void btn_FacturarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FacturarMouseClicked
        if(Tcitas.getSelectedRow() == - 1){
            JOptionPane.showMessageDialog(null, "Seleccione una cita");
        }else{
            for(int i = 0; i < Citas.citas.size(); i++){
                if(Citas.citas.get(i).getId() == Integer.parseInt(Tcitas.getValueAt(Tcitas.getSelectedRow(), 0).toString())){
                    Citas.citas.get(i).concretar(Integer.parseInt(TFtotal.getText()));
                }
            }
            Tcitas.setModel(new DefaultTableModel(Utilidades.FiltrarCitas(new String[] {"", id_cliente}, Citas.citas), columnas));
        }
    }//GEN-LAST:event_btn_FacturarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion_Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion_Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion_Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion_Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion_Windows(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DCfecha;
    private javax.swing.JLabel HOME_ICON;
    private javax.swing.JLabel Label_Fecha;
    private javax.swing.JLabel Label_Lista_clientes;
    private javax.swing.JLabel Label_No_Contacto;
    private javax.swing.JPanel Panel_Tab;
    private javax.swing.JTextField TFnom;
    private javax.swing.JTextField TFtel;
    private javax.swing.JTextField TFtotal;
    private javax.swing.JTable Tcitas;
    private javax.swing.JTable Tresumen;
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btn_Buscar;
    private javax.swing.JLabel btn_Facturar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_Titlulo;
    private javax.swing.JLabel label_titulo_Facturacion1;
    private javax.swing.JLabel label_total;
    private javax.swing.JPanel panel_ResumenServ;
    private javax.swing.JPanel panel_Transparent1;
    private javax.swing.JPanel panel_transparent;
    private javax.swing.JScrollPane scrollpanel_Resumen;
    // End of variables declaration//GEN-END:variables
    private int xx, xy;
}
