package Ventanas;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilda
 */
public class Home_Windows_Contabilidad extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Home_Windows_Contabilidad() {
        initComponents();
        panel_Main.setBackground(new Color (198,214,222,180));
        panel_Transparent1.setBackground(new Color (255,255,255,200));
        panel_Transparent2.setBackground(new Color (255,255,255,200));
        label_HomeM_Icon.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Main = new javax.swing.JPanel();
        panel_Transparent1 = new javax.swing.JPanel();
        label_Home_Icon = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        label_HomeM_Icon = new javax.swing.JLabel();
        panel_Transparent2 = new javax.swing.JPanel();
        btn_Ingresos = new javax.swing.JLabel();
        btn_Inventario = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Main.setBackground(new java.awt.Color(198, 214, 222));
        panel_Main.setEnabled(false);
        panel_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Transparent1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Home_Icon.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        label_Home_Icon.setForeground(new java.awt.Color(105, 87, 86));
        label_Home_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Home_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON_BLUE.png"))); // NOI18N
        label_Home_Icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_Transparent1.add(label_Home_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 50));

        label_title.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        label_title.setForeground(new java.awt.Color(105, 133, 149));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("HOME");
        label_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_Transparent1.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 80));

        label_HomeM_Icon.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        label_HomeM_Icon.setForeground(new java.awt.Color(105, 87, 86));
        label_HomeM_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_HomeM_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON_GREEN.png"))); // NOI18N
        label_HomeM_Icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_HomeM_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_HomeM_IconMouseClicked(evt);
            }
        });
        panel_Transparent1.add(label_HomeM_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 50));

        panel_Main.add(panel_Transparent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        panel_Transparent2.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        javax.swing.GroupLayout panel_Transparent2Layout = new javax.swing.GroupLayout(panel_Transparent2);
        panel_Transparent2.setLayout(panel_Transparent2Layout);
        panel_Transparent2Layout.setHorizontalGroup(
            panel_Transparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        panel_Transparent2Layout.setVerticalGroup(
            panel_Transparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panel_Main.add(panel_Transparent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 850, 70));

        btn_Ingresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Ingresos_White.png"))); // NOI18N
        btn_Ingresos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Ingresos.setFocusable(false);
        btn_Ingresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Ingresos.setMaximumSize(new java.awt.Dimension(204, 36));
        btn_Ingresos.setMinimumSize(new java.awt.Dimension(204, 36));
        btn_Ingresos.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_Ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IngresosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_IngresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_IngresosMouseExited(evt);
            }
        });
        panel_Main.add(btn_Ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 280, 200));

        btn_Inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Inventario_White.png"))); // NOI18N
        btn_Inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Inventario.setFocusable(false);
        btn_Inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Inventario.setMaximumSize(new java.awt.Dimension(204, 36));
        btn_Inventario.setMinimumSize(new java.awt.Dimension(204, 36));
        btn_Inventario.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_InventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_InventarioMouseExited(evt);
            }
        });
        panel_Main.add(btn_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 280, 200));

        getContentPane().add(panel_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 840, 560));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds_Fondo/Contabilidad_bg.jpg"))); // NOI18N
        bgImage.setMaximumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setMinimumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresosMouseEntered
        // TODO add your handling code here:
        btn_Ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Ingresos_Blue.png")));
    }//GEN-LAST:event_btn_IngresosMouseEntered

    private void btn_IngresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresosMouseExited
        // TODO add your handling code here:
        btn_Ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Ingresos_White.png")));
    }//GEN-LAST:event_btn_IngresosMouseExited

    private void btn_InventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventarioMouseEntered
        // TODO add your handling code here: 
        btn_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Inventario_Blue.png"))); 
    }//GEN-LAST:event_btn_InventarioMouseEntered

    private void btn_InventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventarioMouseExited
        // TODO add your handling code here:
        btn_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Inventario_White.png"))); 
    }//GEN-LAST:event_btn_InventarioMouseExited

    private void btn_IngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresosMouseClicked
        // TODO add your handling code here:
        Ingresos_Windows_Contabilidad iwc = new Ingresos_Windows_Contabilidad();
        iwc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_IngresosMouseClicked

    private void btn_InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventarioMouseClicked
        // TODO add your handling code here:
        Inventario_Windows_Contabilidad inwc = new Inventario_Windows_Contabilidad();
        inwc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_InventarioMouseClicked

    private void label_HomeM_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_HomeM_IconMouseClicked
        // TODO add your handling code here:
        Home_Windows_Administrador hwa = new Home_Windows_Administrador();
        hwa.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_label_HomeM_IconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Windows_Contabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Windows_Contabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Windows_Contabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Windows_Contabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Windows_Contabilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btn_Ingresos;
    private javax.swing.JLabel btn_Inventario;
    public javax.swing.JLabel label_HomeM_Icon;
    private javax.swing.JLabel label_Home_Icon;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_Main;
    private javax.swing.JPanel panel_Transparent1;
    private javax.swing.JPanel panel_Transparent2;
    // End of variables declaration//GEN-END:variables
}
