/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Usuarios;
import Clases.Utilidades;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hilda
 */
public class Manejo_Usuarios_Window extends javax.swing.JFrame {

    /**
     * Creates new form Manejo_Usuarios_Window
     */
    String[] Columna = {"Id", "Nombre", "Telefono", "Correo", "Rol", "Sueldo"};
    public Manejo_Usuarios_Window() {
        initComponents();
        panel_Main.setBackground(new Color (145,153,149,200));
        panel_Transparent2.setBackground(new Color (255,255,255,100));
        panel_Transparent3.setBackground(new Color (255,255,255,100));
        
        Tusuarios.setModel(new DefaultTableModel(Utilidades.filtrarEmpleados(new int[] {0, 0, 0}, new String[] {"", "", ""}, Usuarios.Lista_usuarios), Columna));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Main = new javax.swing.JPanel();
        panel_Transparent2 = new javax.swing.JPanel();
        label_Home_Icon = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        label_Home_Icon1 = new javax.swing.JLabel();
        panel_Transparent3 = new javax.swing.JPanel();
        panel_Busqueda = new javax.swing.JPanel();
        label_Nombre = new javax.swing.JLabel();
        TFnom = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        label_No_contacto = new javax.swing.JLabel();
        TFtel = new javax.swing.JTextField();
        TFcorreo = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JLabel();
        Panel_Tabla = new javax.swing.JPanel();
        Label_Lista_Clientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tusuarios = new javax.swing.JTable();
        label_Nombre2 = new javax.swing.JLabel();
        label_No_Contacto = new javax.swing.JLabel();
        label_Email2 = new javax.swing.JLabel();
        label_Sueldo1 = new javax.swing.JLabel();
        label_Sueldo = new javax.swing.JLabel();
        TFnom2 = new javax.swing.JTextField();
        TFtel2 = new javax.swing.JTextField();
        TFcorreo2 = new javax.swing.JTextField();
        TFsueldo = new javax.swing.JTextField();
        CBrol = new javax.swing.JComboBox<>();
        btn_Eliminar = new javax.swing.JLabel();
        btn_Actualizar = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Main.setBackground(new java.awt.Color(145, 153, 149));
        panel_Main.setEnabled(false);
        panel_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Transparent2.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Home_Icon.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        label_Home_Icon.setForeground(new java.awt.Color(105, 87, 86));
        label_Home_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Home_Icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Home_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_Home_IconMouseClicked(evt);
            }
        });
        panel_Transparent2.add(label_Home_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        label_title.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        label_title.setForeground(new java.awt.Color(90, 103, 102));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MANEJO DE USUARIOS");
        label_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_Transparent2.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 80));

        label_Home_Icon1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        label_Home_Icon1.setForeground(new java.awt.Color(105, 87, 86));
        label_Home_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Home_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON_GREEN.png"))); // NOI18N
        label_Home_Icon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Home_Icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_Home_Icon1MouseClicked(evt);
            }
        });
        panel_Transparent2.add(label_Home_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        panel_Main.add(panel_Transparent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 80));

        panel_Transparent3.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_Main.add(panel_Transparent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1160, 50));

        panel_Busqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        panel_Busqueda.setForeground(new java.awt.Color(255, 255, 255));
        panel_Busqueda.setEnabled(false);
        panel_Busqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre.setText("NOMBRE:");
        panel_Busqueda.add(label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        TFnom.setBackground(new java.awt.Color(204, 204, 204));
        TFnom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFnom.setBorder(null);
        TFnom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Busqueda.add(TFnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 390, 39));

        label_Email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Email.setText("CORREO ELECTRONICO:");
        panel_Busqueda.add(label_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 30));

        label_No_contacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_contacto.setText("NO. CONTACTO:");
        panel_Busqueda.add(label_No_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        TFtel.setBackground(new java.awt.Color(204, 204, 204));
        TFtel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFtel.setBorder(null);
        TFtel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Busqueda.add(TFtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 229, 39));

        TFcorreo.setBackground(new java.awt.Color(204, 204, 204));
        TFcorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFcorreo.setBorder(null);
        TFcorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Busqueda.add(TFcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 420, 40));

        btn_Buscar.setBackground(new java.awt.Color(153, 153, 153));
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_White.png"))); // NOI18N
        btn_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BuscarMouseExited(evt);
            }
        });
        panel_Busqueda.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, 40));

        Panel_Tabla.setBackground(new java.awt.Color(90, 103, 102));

        Label_Lista_Clientes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Label_Lista_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Label_Lista_Clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Lista_Clientes.setText("Lista de Empleados");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        Tusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Numero Contacto", "Correo Electronico", "Cargo", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tusuarios);

        javax.swing.GroupLayout Panel_TablaLayout = new javax.swing.GroupLayout(Panel_Tabla);
        Panel_Tabla.setLayout(Panel_TablaLayout);
        Panel_TablaLayout.setHorizontalGroup(
            Panel_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
            .addGroup(Panel_TablaLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(Label_Lista_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_TablaLayout.setVerticalGroup(
            Panel_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Lista_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        panel_Busqueda.add(Panel_Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 830, 130));

        panel_Main.add(panel_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 870, 280));

        label_Nombre2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre2.setText("NOMBRE:");
        panel_Main.add(label_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 90, 30));

        label_No_Contacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_Contacto.setText("NO. CONTACTO:");
        panel_Main.add(label_No_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 130, 30));

        label_Email2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Email2.setText("CORREO ELECTRONICO:");
        panel_Main.add(label_Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 180, 30));

        label_Sueldo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Sueldo1.setText("ROL:");
        panel_Main.add(label_Sueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 40, 40));

        label_Sueldo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Sueldo.setText("SUELDO:");
        panel_Main.add(label_Sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 60, 40));

        TFnom2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFnom2.setBorder(null);
        TFnom2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Main.add(TFnom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 740, 40));

        TFtel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFtel2.setBorder(null);
        TFtel2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Main.add(TFtel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 260, 40));

        TFcorreo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFcorreo2.setBorder(null);
        TFcorreo2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Main.add(TFcorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 330, 40));

        TFsueldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFsueldo.setBorder(null);
        TFsueldo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_Main.add(TFsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 330, 40));

        CBrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "recepcionista", "Gerente" }));
        panel_Main.add(CBrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 260, 40));

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Eliminar_Cliente_White.png"))); // NOI18N
        btn_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EliminarMouseExited(evt);
            }
        });
        panel_Main.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, -1, 40));

        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Actualizar_White.png"))); // NOI18N
        btn_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ActualizarMouseExited(evt);
            }
        });
        panel_Main.add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, 40));

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Agregar_Usuario_White.png"))); // NOI18N
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseExited(evt);
            }
        });
        panel_Main.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, 40));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds_Fondo/Management_bg_MEDIUM.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_Home_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_Home_IconMouseClicked
        // TODO add your handling code here:
        Home_Windows_Administrador hwa = new Home_Windows_Administrador();
        hwa.setVisible(true);
        dispose();
    }//GEN-LAST:event_label_Home_IconMouseClicked

    private void label_Home_Icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_Home_Icon1MouseClicked
        // TODO add your handling code here:
        Home_Windows_Administrador hwa = new Home_Windows_Administrador();
        hwa.setVisible(true);
        dispose();
    }//GEN-LAST:event_label_Home_Icon1MouseClicked

    private void btn_BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseEntered
        // TODO add your handling code here:
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_Brown.png")));
    }//GEN-LAST:event_btn_BuscarMouseEntered

    private void btn_BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseExited
        // TODO add your handling code here:
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Buscar_White.png")));
    }//GEN-LAST:event_btn_BuscarMouseExited

    private void btn_ActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarMouseEntered
        // TODO add your handling code here:
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Actualizar_Brown.png"))); 
        
    }//GEN-LAST:event_btn_ActualizarMouseEntered

    private void btn_ActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarMouseExited
        // TODO add your handling code here:
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Actualizar_White.png"))); 
    }//GEN-LAST:event_btn_ActualizarMouseExited

    private void btn_EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarMouseEntered
        // TODO add your handling code here:
        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Eliminar_Cliente_Brown.png")));
    }//GEN-LAST:event_btn_EliminarMouseEntered

    private void btn_EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarMouseExited
        // TODO add your handling code here:
        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Eliminar_Cliente_White.png")));
    }//GEN-LAST:event_btn_EliminarMouseExited

    private void btn_AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseEntered
        // TODO add your handling code here:
        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Agregar_Usuario_Brown.png")));
    }//GEN-LAST:event_btn_AgregarMouseEntered

    private void btn_AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseExited
        // TODO add your handling code here:
        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Agregar_Usuario_White.png")));
    }//GEN-LAST:event_btn_AgregarMouseExited

    private void TusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TusuariosMouseClicked
        int sl = Tusuarios.getSelectedRow();
        switch(sl){
            case -1 -> {
                TFnom2.setText("");
                TFtel2.setText("");
                TFcorreo2.setText("s");
            }
            default -> {
                TFnom2.setText(Tusuarios.getValueAt(sl, 1).toString());
                TFtel2.setText(Tusuarios.getValueAt(sl, 2).toString());
                TFcorreo2.setText(Tusuarios.getValueAt(sl, 3).toString());
                TFsueldo.setText(Tusuarios.getValueAt(sl, 5).toString());
                CBrol.setSelectedItem(Tusuarios.getValueAt(sl, 4));
            }
        }
    }//GEN-LAST:event_TusuariosMouseClicked

    private void btn_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BuscarMouseClicked
        int f1 = TFnom.getText().equals("")? 0: 1;
        int f2 = TFtel.getText().equals("")? 0: 1;
        int f3 = TFcorreo.getText().equals("")? 0: 1;
        
        int[] filtros = {f1, f2, f3};
        
        String[] values = {TFnom.getText(), TFtel.getText(), TFcorreo.getText()};
        
        Tusuarios.setModel(new DefaultTableModel(Clases.Utilidades.filtrarEmpleados(filtros,values, Usuarios.Lista_usuarios), Columna));
    }//GEN-LAST:event_btn_BuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manejo_Usuarios_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manejo_Usuarios_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manejo_Usuarios_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manejo_Usuarios_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manejo_Usuarios_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBrol;
    private javax.swing.JLabel Label_Lista_Clientes;
    private javax.swing.JPanel Panel_Tabla;
    private javax.swing.JTextField TFcorreo;
    private javax.swing.JTextField TFcorreo2;
    private javax.swing.JTextField TFnom;
    private javax.swing.JTextField TFnom2;
    private javax.swing.JTextField TFsueldo;
    private javax.swing.JTextField TFtel;
    private javax.swing.JTextField TFtel2;
    private javax.swing.JTable Tusuarios;
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btn_Actualizar;
    private javax.swing.JLabel btn_Agregar;
    private javax.swing.JLabel btn_Buscar;
    private javax.swing.JLabel btn_Eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Email2;
    private javax.swing.JLabel label_Home_Icon;
    private javax.swing.JLabel label_Home_Icon1;
    private javax.swing.JLabel label_No_Contacto;
    private javax.swing.JLabel label_No_contacto;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_Nombre2;
    private javax.swing.JLabel label_Sueldo;
    private javax.swing.JLabel label_Sueldo1;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_Busqueda;
    private javax.swing.JPanel panel_Main;
    private javax.swing.JPanel panel_Transparent2;
    private javax.swing.JPanel panel_Transparent3;
    // End of variables declaration//GEN-END:variables
}
