package Ventanas;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilda
 */
public class Registration_Window extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Registration_Window() {
        initComponents();
        panel_Registration.setBackground(new Color (212,176,155,200));
        panel_Transparent1.setBackground(new Color (255,255,255,200));
        panel_Transparent2.setBackground(new Color (255,255,255,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Transparent3 = new javax.swing.JPanel();
        label_titulo1 = new javax.swing.JLabel();
        HOME_ICON = new javax.swing.JLabel();
        panel_Registration = new javax.swing.JPanel();
        label_Nombre = new javax.swing.JLabel();
        TFnombre = new javax.swing.JTextField();
        label_No_Contacto = new javax.swing.JLabel();
        TFtel = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        TFmail = new javax.swing.JTextField();
        btn_Registra = new javax.swing.JLabel();
        panel_Transparent1 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        panel_Transparent2 = new javax.swing.JPanel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Transparent3.setBackground(new java.awt.Color(255, 255, 255));

        label_titulo1.setBackground(new java.awt.Color(105, 87, 86));
        label_titulo1.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        label_titulo1.setForeground(new java.awt.Color(105, 87, 86));
        label_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo1.setText("BEAUTY SALON & SPA");
        label_titulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HOME_ICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON.png"))); // NOI18N
        HOME_ICON.setFocusable(false);
        HOME_ICON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HOME_ICON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOME_ICONMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_Transparent3Layout = new javax.swing.GroupLayout(panel_Transparent3);
        panel_Transparent3.setLayout(panel_Transparent3Layout);
        panel_Transparent3Layout.setHorizontalGroup(
            panel_Transparent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Transparent3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(label_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        panel_Transparent3Layout.setVerticalGroup(
            panel_Transparent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Transparent3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Transparent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(HOME_ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Transparent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 60));

        panel_Registration.setBackground(new java.awt.Color(212, 176, 155));
        panel_Registration.setAutoscrolls(true);
        panel_Registration.setEnabled(false);
        panel_Registration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre.setText("NOMBRE:");
        panel_Registration.add(label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 90, 30));

        TFnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFnombre.setBorder(null);
        TFnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });
        panel_Registration.add(TFnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 390, 40));

        label_No_Contacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_Contacto.setText("NO. CONTACTO:");
        panel_Registration.add(label_No_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, 30));

        TFtel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFtel.setBorder(null);
        TFtel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtelActionPerformed(evt);
            }
        });
        panel_Registration.add(TFtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 390, 40));

        label_Email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Email.setText("CORREO ELECTRONICO:");
        panel_Registration.add(label_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 30));

        TFmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFmail.setBorder(null);
        TFmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFmailActionPerformed(evt);
            }
        });
        panel_Registration.add(TFmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 390, 40));

        btn_Registra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Registra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Registrar.png"))); // NOI18N
        btn_Registra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Registra.setDoubleBuffered(true);
        btn_Registra.setFocusable(false);
        btn_Registra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Registra.setMaximumSize(new java.awt.Dimension(204, 36));
        btn_Registra.setMinimumSize(new java.awt.Dimension(204, 36));
        btn_Registra.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_Registra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegistraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RegistraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RegistraMouseExited(evt);
            }
        });
        panel_Registration.add(btn_Registra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 210, 40));

        panel_Transparent1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Palatino Linotype", 0, 48)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(105, 87, 86));
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Registrar Cliente");
        label_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_Transparent1.add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 390, 70));

        panel_Registration.add(panel_Transparent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, 80));

        panel_Transparent2.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_Registration.add(panel_Transparent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 750, 60));

        getContentPane().add(panel_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 750, 490));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds_Fondo/login_bg.jpg"))); // NOI18N
        bgImage.setMaximumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setMinimumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setPreferredSize(new java.awt.Dimension(500, 600));
        bgImage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgImageMouseDragged(evt);
            }
        });
        bgImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgImageMousePressed(evt);
            }
        });
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void bgImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgImageMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgImageMousePressed

    private void TFtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtelActionPerformed

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnombreActionPerformed

    private void TFmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFmailActionPerformed

    private void bgImageMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgImageMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();

	int y = evt.getYOnScreen();

	Registration_Window.this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bgImageMouseDragged

    private void btn_RegistraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistraMouseEntered
        // TODO add your handling code here:
        btn_Registra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Registrar_Entered.png")));
    }//GEN-LAST:event_btn_RegistraMouseEntered

    private void btn_RegistraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistraMouseExited
        // TODO add your handling code here:
        //btn_Iniciar_Ses.setBorder(RoundRectangle2D);
        btn_Registra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Registrar.png")));
    }//GEN-LAST:event_btn_RegistraMouseExited

    private void btn_RegistraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistraMouseClicked
       new Clases.Clientes().agregar(new String[] {TFnombre.getText(), TFtel.getText(), TFmail.getText()});
       clearRegistration_Window();
    }//GEN-LAST:event_btn_RegistraMouseClicked

    private void HOME_ICONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseClicked
        SQL.Guardar.guardar();
        new Home_Windows().setVisible(true);
        dispose();
    }//GEN-LAST:event_HOME_ICONMouseClicked

    private void HOME_ICONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseEntered
        // TODO add your handling code here:
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON_LIGHTBROWN.png")));
    }//GEN-LAST:event_HOME_ICONMouseEntered

    private void HOME_ICONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOME_ICONMouseExited
        // TODO add your handling code here:
        HOME_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HOME_ICON.png")));
    }//GEN-LAST:event_HOME_ICONMouseExited

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden
    private void clearRegistration_Window(){
        TFnombre.setText("");
        TFtel.setText("");
        TFmail.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HOME_ICON;
    private javax.swing.JTextField TFmail;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JTextField TFtel;
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btn_Registra;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_No_Contacto;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_titulo1;
    private javax.swing.JPanel panel_Registration;
    private javax.swing.JPanel panel_Transparent1;
    private javax.swing.JPanel panel_Transparent2;
    private javax.swing.JPanel panel_Transparent3;
    // End of variables declaration//GEN-END:variables
    private int xx, xy;
}
