package Ventanas;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilda
 */
public class Registration_Window extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Registration_Window() {
        initComponents();
        panel_Registration.setBackground(new Color (212,176,155,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Registration = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        label_No_Contacto = new javax.swing.JLabel();
        textField_No_contacto_input = new javax.swing.JTextField();
        btn_Registrar = new javax.swing.JButton();
        label_Nombre = new javax.swing.JLabel();
        textField_Client_Name_input = new javax.swing.JTextField();
        textField_Email_input = new javax.swing.JTextField();
        label_No_Contacto1 = new javax.swing.JLabel();
        label_No_Contacto2 = new javax.swing.JLabel();
        textField_Email_input1 = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Registration.setBackground(new java.awt.Color(212, 176, 155));
        panel_Registration.setEnabled(false);

        label_titulo.setFont(new java.awt.Font("Palatino Linotype", 0, 40)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(0, 0, 0));
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Registrar Cliente");
        label_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        label_No_Contacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_Contacto.setForeground(new java.awt.Color(0, 0, 0));
        label_No_Contacto.setText("NO. CONTACTO:");

        textField_No_contacto_input.setBackground(new java.awt.Color(255, 255, 255));
        textField_No_contacto_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_No_contacto_input.setForeground(new java.awt.Color(0, 0, 0));
        textField_No_contacto_input.setText(" ");
        textField_No_contacto_input.setBorder(null);
        textField_No_contacto_input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_No_contacto_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_No_contacto_inputActionPerformed(evt);
            }
        });

        btn_Registrar.setBackground(new java.awt.Color(128, 76, 45));
        btn_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Registrar.setText("Registrar");
        btn_Registrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 76, 46), 5, true));
        btn_Registrar.setBorderPainted(false);

        label_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        label_Nombre.setText("NOMBRE:");

        textField_Client_Name_input.setBackground(new java.awt.Color(255, 255, 255));
        textField_Client_Name_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_Client_Name_input.setForeground(new java.awt.Color(0, 0, 0));
        textField_Client_Name_input.setText(" ");
        textField_Client_Name_input.setBorder(null);
        textField_Client_Name_input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_Client_Name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Client_Name_inputActionPerformed(evt);
            }
        });

        textField_Email_input.setBackground(new java.awt.Color(255, 255, 255));
        textField_Email_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_Email_input.setForeground(new java.awt.Color(0, 0, 0));
        textField_Email_input.setText(" ");
        textField_Email_input.setBorder(null);
        textField_Email_input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_Email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Email_inputActionPerformed(evt);
            }
        });

        label_No_Contacto1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_Contacto1.setForeground(new java.awt.Color(0, 0, 0));
        label_No_Contacto1.setText("CORREO ELECTRONICO:");

        label_No_Contacto2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_No_Contacto2.setForeground(new java.awt.Color(0, 0, 0));
        label_No_Contacto2.setText("DIRECCION:");

        textField_Email_input1.setBackground(new java.awt.Color(255, 255, 255));
        textField_Email_input1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_Email_input1.setForeground(new java.awt.Color(0, 0, 0));
        textField_Email_input1.setText(" ");
        textField_Email_input1.setBorder(null);
        textField_Email_input1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_Email_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Email_input1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_RegistrationLayout = new javax.swing.GroupLayout(panel_Registration);
        panel_Registration.setLayout(panel_RegistrationLayout);
        panel_RegistrationLayout.setHorizontalGroup(
            panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RegistrationLayout.createSequentialGroup()
                .addGroup(panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_RegistrationLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(label_No_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textField_No_contacto_input, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_RegistrationLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label_No_Contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textField_Email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_RegistrationLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(label_No_Contacto2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textField_Email_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_RegistrationLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(label_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(textField_Client_Name_input))))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_RegistrationLayout.createSequentialGroup()
                .addComponent(btn_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        panel_RegistrationLayout.setVerticalGroup(
            panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RegistrationLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_Client_Name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_No_contacto_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_No_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_Email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_No_Contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel_RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_Email_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_No_Contacto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(btn_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 690, 560));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setToolTipText("");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 30));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_bg.jpg"))); // NOI18N
        bgImage.setMaximumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setMinimumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setPreferredSize(new java.awt.Dimension(500, 600));
        bgImage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgImageMouseDragged(evt);
            }
        });
        bgImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgImageMousePressed(evt);
            }
        });
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bgImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgImageMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgImageMousePressed

    private void textField_No_contacto_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_No_contacto_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_No_contacto_inputActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarMousePressed

    private void textField_Client_Name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Client_Name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Client_Name_inputActionPerformed

    private void textField_Email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Email_inputActionPerformed

    private void textField_Email_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Email_input1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textField_Email_input1ActionPerformed

    private void bgImageMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgImageMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();

	int y = evt.getYOnScreen();

	Registration_Window.this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bgImageMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JLabel label_No_Contacto;
    private javax.swing.JLabel label_No_Contacto1;
    private javax.swing.JLabel label_No_Contacto2;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel panel_Registration;
    private javax.swing.JTextField textField_Client_Name_input;
    private javax.swing.JTextField textField_Email_input;
    private javax.swing.JTextField textField_Email_input1;
    private javax.swing.JTextField textField_No_contacto_input;
    // End of variables declaration//GEN-END:variables
    private int xx, xy;
}
