package Ventanas;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilda
 */
public class Reservacion extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Reservacion() {
        initComponents();
        panel_Transparent1.setBackground(new Color (212,176,155,200));
        panel_Transparent2.setBackground(new Color (255,255,255,100));
        panel_Transparent3.setBackground(new Color (255,255,255,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Transparent1 = new javax.swing.JPanel();
        panel_Transparent2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Transparent3 = new javax.swing.JPanel();
        btn_Cliente_Nuevo = new javax.swing.JLabel();
        btn_Cliente_Registrado = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Transparent1.setBackground(new java.awt.Color(212, 176, 155));
        panel_Transparent1.setEnabled(false);
        panel_Transparent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Transparent2.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservación");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_Transparent2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 70));

        panel_Transparent1.add(panel_Transparent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 860, 70));

        panel_Transparent3.setBackground(new java.awt.Color(255, 255, 255));
        panel_Transparent3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panel_Transparent3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_Transparent1.add(panel_Transparent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 860, 60));

        btn_Cliente_Nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cliente_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Cliente_nuevo_Entered.png"))); // NOI18N
        btn_Cliente_Nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cliente_Nuevo.setFocusable(false);
        btn_Cliente_Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Cliente_Nuevo.setMaximumSize(new java.awt.Dimension(204, 36));
        btn_Cliente_Nuevo.setMinimumSize(new java.awt.Dimension(204, 36));
        btn_Cliente_Nuevo.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_Cliente_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cliente_NuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cliente_NuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cliente_NuevoMouseExited(evt);
            }
        });
        panel_Transparent1.add(btn_Cliente_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 280, 200));

        btn_Cliente_Registrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cliente_Registrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Btn_Cliente_Registrado.png"))); // NOI18N
        btn_Cliente_Registrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cliente_Registrado.setFocusable(false);
        btn_Cliente_Registrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Cliente_Registrado.setMaximumSize(new java.awt.Dimension(204, 36));
        btn_Cliente_Registrado.setMinimumSize(new java.awt.Dimension(204, 36));
        btn_Cliente_Registrado.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_Cliente_Registrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cliente_RegistradoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cliente_RegistradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cliente_RegistradoMouseExited(evt);
            }
        });
        panel_Transparent1.add(btn_Cliente_Registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 280, 200));

        getContentPane().add(panel_Transparent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 860, 560));

        bgImage.setBackground(new java.awt.Color(212, 176, 155));
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg_Registros.jpg"))); // NOI18N
        bgImage.setMaximumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setMinimumSize(new java.awt.Dimension(1000, 2000));
        bgImage.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Cliente_RegistradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cliente_RegistradoMouseClicked
        // TODO add your handling code here:

        //btn_Cliente_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_Registrar.png")));
    }//GEN-LAST:event_btn_Cliente_RegistradoMouseClicked

    private void btn_Cliente_RegistradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cliente_RegistradoMouseEntered
        // TODO add your handling code here:
        btn_Cliente_Registrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Cliente_Registrado_Entered.png")));
    }//GEN-LAST:event_btn_Cliente_RegistradoMouseEntered

    private void btn_Cliente_RegistradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cliente_RegistradoMouseExited
        // TODO add your handling code here:
        //btn_Iniciar_Ses.setBorder(RoundRectangle2D);
        btn_Cliente_Registrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Cliente_Registrado.png"))); 
    }//GEN-LAST:event_btn_Cliente_RegistradoMouseExited

    private void btn_Cliente_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cliente_NuevoMouseClicked
        // TODO add your handling code here:
        Registration_Window RW = new Registration_Window();
        RW.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Cliente_NuevoMouseClicked

    private void btn_Cliente_NuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cliente_NuevoMouseEntered
        // TODO add your handling code here:
        btn_Cliente_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Cliente_nuevo.png")));
    }//GEN-LAST:event_btn_Cliente_NuevoMouseEntered

    private void btn_Cliente_NuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cliente_NuevoMouseExited
        // TODO add your handling code here:
        btn_Cliente_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/btn_Cliente_nuevo_Entered.png")));
    }//GEN-LAST:event_btn_Cliente_NuevoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel btn_Cliente_Nuevo;
    private javax.swing.JLabel btn_Cliente_Registrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_Transparent1;
    private javax.swing.JPanel panel_Transparent2;
    private javax.swing.JPanel panel_Transparent3;
    // End of variables declaration//GEN-END:variables
}
